name: Deploy to VPS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Build the app with Expo
      run: |
        npm install
        npx expo export --platform web

    - name: Deploy to VPS using rsync
      run: |
        rsync -avz --delete ./dist/ gabriel@${{ secrets.VPS_IP }}:/var/www/mifincaapp/

    - name: Restart Nginx
      run: |
        ssh gabriel@${{ secrets.VPS_IP }} 'sudo systemctl restart nginx'
